// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtHwBw-42uLGfuuN3L29UepnzAOGrkCYw',
    appId: '1:166946871603:web:10f964411a9bdf4fbf4646',
    messagingSenderId: '166946871603',
    projectId: 'smartshopuser-2ef7d',
    authDomain: 'smartshopuser-2ef7d.firebaseapp.com',
    storageBucket: 'smartshopuser-2ef7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiKz23wfG2fpV08ND2nb2Yt3D5b4wGJ5A',
    appId: '1:166946871603:android:988e95134d062d7fbf4646',
    messagingSenderId: '166946871603',
    projectId: 'smartshopuser-2ef7d',
    storageBucket: 'smartshopuser-2ef7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuAIT0NSSFkA53stISLGh7MH-TamDl6mg',
    appId: '1:166946871603:ios:d18ee0ac7f02e95dbf4646',
    messagingSenderId: '166946871603',
    projectId: 'smartshopuser-2ef7d',
    storageBucket: 'smartshopuser-2ef7d.appspot.com',
    androidClientId: '166946871603-4vanli3h5sk9dpbrppep1hfsd81gl8rs.apps.googleusercontent.com',
    iosClientId: '166946871603-fp7qjag8sd1qcqmi654ts7agurmnvk9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoopSmartAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuAIT0NSSFkA53stISLGh7MH-TamDl6mg',
    appId: '1:166946871603:ios:b18c599744f5bd18bf4646',
    messagingSenderId: '166946871603',
    projectId: 'smartshopuser-2ef7d',
    storageBucket: 'smartshopuser-2ef7d.appspot.com',
    androidClientId: '166946871603-4vanli3h5sk9dpbrppep1hfsd81gl8rs.apps.googleusercontent.com',
    iosClientId: '166946871603-b6nh8lmdv24qjv8f6ieubhdveliq3390.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoopSmartAdmin.RunnerTests',
  );
}
